project_name: sn-cli

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy

builds:
  - id: sn-macos
    main: ./cmd/sncli/
    binary: sn
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"
    hooks:
      post: |
        sh -c '
        cat > /tmp/sn-cli-gon-amd64.hcl << EOF
        source = ["./dist/sn-macos_darwin_amd64/sn"]
        bundle_id = "uk.co.lessknown.sn-cli"
        apple_id {
          username = "jon@lessknown.co.uk"
          password = "@env:AC_PASSWORD"
        }
        sign {
          application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
        }
        zip {
          output_path = "./dist/sn-cli_Darwin_amd64.zip"
        }
        EOF
        gon /tmp/sn-cli-gon-amd64.hcl
        '

  - id: sn-macos-arm
    main: ./cmd/sncli/
    binary: sn
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"
    hooks:
      post: |
        sh -c '
        cat > /tmp/sn-cli-gon-arm64.hcl << EOF
        source = ["./dist/sn-macos-arm_darwin_arm64/sn"]
        bundle_id = "uk.co.lessknown.sn-cli"
        apple_id {
          username = "jon@lessknown.co.uk"
          password = "@env:AC_PASSWORD"
        }
        sign {
          application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
        }
        zip {
          output_path = "./dist/sn-cli_Darwin_arm64.zip"
        }
        EOF
        gon /tmp/sn-cli-gon-arm64.hcl
        '
  - id: sn
    main: ./cmd/sncli/
    binary: sn
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - "-X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    builds:
      - sn
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

release:
  github:
    owner: jonhadfield
    name: sn-cli
  prerelease: auto
  name_template: '{{ .Tag }}'
  extra_files:
    - glob: ./dist/sn-cli_Darwin*.zip

announce:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
    - README
    - test
    - ignore

checksum:
  name_template: 'checksums.txt'