project_name: sn-cli

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy

# join mac binaries into one
universal_binaries:
  - id: sn-macos-universal
    ids:
      - sn-macos
      - sn-macos-arm
    name_template: "sn"
    replace: true
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post: |
        sh -c '
        cat > /tmp/sn-cli-gon-universal.hcl << EOF
        source = ["./dist/sn-macos_darwin_universal/sn"]
        bundle_id = "uk.co.lessknown.sn-cli"
        apple_id {
          username = "jon@lessknown.co.uk"
          password = "@env:AC_PASSWORD"
        }
        sign {
          application_identity = "Developer ID Application: Jonathan Hadfield (VBZY8FBYR5)"
        }
        zip {
          output_path = "./dist/sn-cli_Darwin_universal.zip"
        }
        EOF
        gon /tmp/sn-cli-gon-universal.hcl
        '

builds:
  - id: sn-macos
    main: ./cmd/sncli/
    binary: sn
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

  - id: sn-macos-arm
    main: ./cmd/sncli/
    binary: sn
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

  - id: sn
    main: ./cmd/sncli/
    binary: sn
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.sha={{ .ShortCommit }} -X main.buildDate={{ .Date }} -X main.tag={{ .Tag }}"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "linux" }}Linux_
      {{- else if eq .Os "windows" }}Windows_
      {{- else }}{{- tolower .Os }}_{{ end -}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end -}}
      {{ if .Arm }}v{{ .Arm }}{{ end -}}
    builds:
      - sn
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

release:
  github:
    owner: jonhadfield
    name: sn-cli
  prerelease: auto
  name_template: '{{ .Tag }}'
  extra_files:
    - glob: ./dist/sn-cli_Darwin*.zip

announce:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
    - README
    - test
    - ignore

checksum:
  name_template: 'checksums.txt'
